name: Get Boogie
description: Derives third-party dependencies for Dove needed to prove.
author: Pontem Network team
branding:
  icon: "sunrise"
  color: "purple"
inputs:
  ref:
    description: Branch or commit pointing to pontem-network/move repo. Read as version of installer. Default is `main`.
    default: main
    required: false
  token:
    description: GITHUB_TOKEN. Optional
    required: false
outputs:
  DOTNET_ROOT:
    description: .NET root directory
    value: ${{ steps.installer.outputs.DOTNET_ROOT }}
  Z3_EXE:
    description: Z3 executable path
    value: ${{ steps.installer.outputs.Z3_EXE }}
  BOOGIE_EXE:
    description: Boogie executable path
    value: ${{ steps.installer.outputs.BOOGIE_EXE }}
  CVC5_EXE:
    description: Cvc5 executable path
    value: ${{ steps.installer.outputs.CVC5_EXE }}
runs:
  using: composite
  steps:
    - id: installer
      shell: bash
      run: |
        if [ ! "$RUNNER_OS" == "Windows" ]; then
             sudo chown runner ${{ github.action_path }}/installer.sh && chmod +x ${{ github.action_path }}/installer.sh
        fi
        $GITHUB_ACTION_PATH/installer.sh
      env:
        INP_REF: ${{inputs.ref || 'main'}}
        SECRET_TOKEN: ${{inputs.token}}
